### ISSUE TITLE
노이슈타트로 분수대 이벤트 칭호 획득시 크래시

### ISSUE THREAD

**Issue by lky20004** [ToD-DC-Kor/kor-patch#10]
체리크에서 노이슈타트로  돌아와서 분수대 이벤트 두곳에서 프리징발생후 멈춤

첨부한 세이브 파일 로드 세이프 6번째 여관에서 나오면

분수대 파란옷아이 소디언을 알고 있는거야 선택후 마지막에  프리징발생후 멈춤

분수대 달리기 이벤트 승리후 프리징발생후 멈춤

 패치 버전: v0.3.1
 PCSX2  2.0.2 

[Mcd001.zip](https://github.com/user-attachments/files/16732786/Mcd001.zip)

![Tales of Destiny  Director's Cut _SLPS-25842_20240824031751](https://github.com/user-attachments/assets/e3792690-dca9-43f5-a129-2ee5feec6808)
![Tales of Destiny  Director's Cut _SLPS-25842_20240824032244](https://github.com/user-attachments/assets/fefeff6a-a4b3-4151-bb85-68eeb0b709f9)
![Tales of Destiny  Director's Cut _SLPS-25842_20240824032248](https://github.com/user-attachments/assets/6e1f3bb9-269f-47e9-be97-d08d47baf22d)

**Comment by kexplo** [comment]
'소디언을 알고 있는거야' 선택지 후 크래시 문제가 한국어 패치 판에서만 발생하는군요. 패치 이슈가 맞아보입니다.

**Comment by kexplo** [comment]
![Tales of Destiny  Director's Cut _SLPS-25842_20240831124206](https://github.com/user-attachments/assets/a2300f34-c10b-430c-b3a1-a34d0af28758)

소디언 칭호 이슈는 원인 찾았고, 정리해서 패치 예정입니다.

**Comment by kexplo** [comment]
v0.4.1 수정 패치 배포
