### ISSUE TITLE
폰트 어긋남이슈

### ISSUE THREAD

**Issue by kexplo** [ToD-DC-Kor/kor-patch#13]
퍼스트버튼 님 제보

![폰트 정렬](https://github.com/user-attachments/assets/ddb2b69d-f5f1-4620-af82-8ff70e68ca6e)

**Comment by dj5927** [comment]
추가적으로 폰트간격과 상하라인도 글자마다 조금씩 다른문제가 있습니다~

**Comment by kexplo** [comment]
폰트가 특정 범위 이후로 몇 픽셀씩 밀려서 만들어진 문제였었고, 새로 변환해서 수정했습니다. v0.8.0 이후로 교정된 폰트가 사용됩니다.

밀린 폰트 교정 전/후 비교 GIF:

![Image](https://github.com/user-attachments/assets/490c5670-d932-4d9c-ba77-afe39846cb3f)
