### ISSUE TITLE
작은배를 타고 모리유성 진입시 프리징현상

### ISSUE THREAD

**Issue by asdwewe34** [ToD-DC-Kor/kor-patch#14]
**버그에 대한 설명**
조니가 성으로 간후 주인공들도 성으로 가야하는데 배타고 진입시 프리징현상 발생..

**재현 방법**
재현 방법이 명확하다면, 문제를 재현할 수 있는 재현 방법을 적어주세요.
1. 첨부한 세이브 파일 로드. (세이브 첨부시 '상태 저장' 파일말고 메모리 카드 파일을 첨부해주세요)
2. 바로 앞의 NPC 말걸기
3. 메모리 카드 다시 올렸습니다

**기대 결과**
버그가 없을 경우 원래 기대되는 결과를 적어주세요.

**스크린샷**
가능하다면 도움이 되는 스크린샷을 첨부해주세요

**실행 환경:**
 - 패치 버전: 0.2.1
 - PCSX2 버전:2.1.1
![제목 없음](https://github.com/user-attachments/assets/4ec8c64c-0da6-4df2-9d44-089ef590010b)

**체크 리스트**
- [x] 해당하는 항목을 'x' 체크해주세요
- [ ] 한국어 패치 되지 않은 버전에서도 똑같이 문제가 발생합니다
- [x] 한국어 패치 된 버전에서만 문제가 발생합니다
- [x] v0.2.1 버전 이후에 작성된 세이브 파일로 진행했습니다
- [x] 최신 한국어 패치 버전을 사용했습니다
- [ ] [Mcd001.zip](https://github.com/user-attachments/files/16828773/Mcd001.zip)

**Comment by kexplo** [comment]
세이브파일 재현 방법 적어주세요.

**Comment by asdwewe34** [comment]
다시 올렷습니다.

**Comment by kexplo** [comment]
최신 한국어 패치로 진행한 게 맞나요? 배 탔을 때 여전히 프리징이 재현되지 않습니다.

![image](https://github.com/user-attachments/assets/92e9d9ab-2ac5-4724-ab0b-cd835a5b7146)
![image](https://github.com/user-attachments/assets/b6991dbc-d7be-4b58-a7d6-65257c4add1e)
![image](https://github.com/user-attachments/assets/1655acba-caf2-472a-97f7-5f18b13d6df9)
![image](https://github.com/user-attachments/assets/853ffa8f-7432-47f3-93af-3417d208778c)

**Comment by asdwewe34** [comment]
그렇군여.. 감사합니다

**Comment by kexplo** [comment]
v0.2.1에서 발생하던 문제일 수 있으니 최신 v0.4.2로 플레이 해보세요
