### ISSUE TITLE
0.4.1 패치후 생긴 번역오류

### ISSUE THREAD

**Issue by dj5927** [ToD-DC-Kor/kor-patch#15]
**번역 오류에 대한 설명**
간결하고 명료하게 어떤 문제인지 설명해주세요.

**재현 방법**
재현 방법이 명확하고 작업자가 재현해서 살펴봐야 하는 문제라면, 문제를 재현할 수 있는 재현 방법을 적어주세요.
1. 첨부한 세이브 파일 로드
2. 바로 앞의 NPC 말걸기
3. ...

**스크린샷**
가능하다면 도움이 되는 스크린샷을 첨부해주세요. 번역 오류는 스크린샷이 크게 도움 됩니다.

**실행 환경:**
 - 패치 버전:  0.4.1
 - PCSX2 버전: 2.0.2

**추가 정보**
0.4.1 패치후 처음부터 다시 진행해보고 있는데
기존에는 없던 일어가 섞여나오는 대사가 많아졌습니다.

발견한 몇가지 사진으로 등록하겠습니다.
[
![20240901_034911](https://github.com/user-attachments/assets/9f354cfc-8831-400f-90ba-20b474828bc3)
![20240901_034837](https://github.com/user-attachments/assets/90a90226-2159-41f4-b9b0-965af43e6a8b)
![20240901_034045](https://github.com/user-attachments/assets/9ec3a181-fb19-47ea-a9cb-2ee0f54e0e83)
![20240901_033608](https://github.com/user-attachments/assets/4b4a6d01-bf8e-402a-9693-ce60e057a51e)
![20240901_033436](https://github.com/user-attachments/assets/3ba2436d-5541-416c-bacd-2ff4878f12b7)
![20240901_030359](https://github.com/user-attachments/assets/943e2295-802e-454f-8856-a6cd84b66254)
![20240901_024650](https://github.com/user-attachments/assets/01157650-1d20-4c4b-a82e-5452e5d94d0b)
](url)

**Comment by kexplo** [comment]
여러가지 오류가 섞여있는 것으로 보입니다.

- (1) 번역 오류 https://github.com/ToD-DC-Kor/kor-patch/blob/fe962f11e19215ee59ecf97ae79ea1f000c11eb0/translations/RSCE/13692_75.txt#L557-L558
- (2) 번역 오류 https://github.com/ToD-DC-Kor/kor-patch/blob/fe962f11e19215ee59ecf97ae79ea1f000c11eb0/translations/RSCE/13692_75.txt#L534-L535
- (3) 번역 오류 https://github.com/ToD-DC-Kor/kor-patch/blob/fe962f11e19215ee59ecf97ae79ea1f000c11eb0/translations/RSCE/13667_70.txt#L743-L744
- (4) 번역 오류 https://github.com/ToD-DC-Kor/kor-patch/blob/fe962f11e19215ee59ecf97ae79ea1f000c11eb0/translations/RSCE/13675_82.txt#L301-L302
- (5) 번역 오류 & 0.4.1 패치후 생긴 글자 오류 https://github.com/ToD-DC-Kor/kor-patch/blob/fe962f11e19215ee59ecf97ae79ea1f000c11eb0/translations/RSCE/13675_82.txt#L129-L130
- (6) 미번역된 문자열 (추출 과정에서 놓쳤을 것으로 추정)
- (7) 0.4.1 패치후 생긴 글자 오류

6번의 경우 추출 대상을 파악하기 위해, 재현할 수 있는 상황/조건이 더 필요합니다.
7번의 경우는 원인을 파악해서 고쳤기 때문에, 아마 다른 경우도 같이 해결되었을 것이라 추정합니다. 재현 가능한 초반 케이스만 확인했습니다.

![Tales of Destiny  Director's Cut _SLPS](https://github.com/user-attachments/assets/fad7e40a-04cd-4680-8601-4b489e82e80e)

제보 안 해주셨으면 몰랐겠네요. 덕분에 6번 케이스를 제외하고는 수정하여 다음 패치 예정입니다.

**Comment by kexplo** [comment]
v0.4.2 패치로 수정됨
