### ISSUE TITLE
미번역된 문자열: 아이템 가득참

### ISSUE THREAD

**Issue by kexplo** [ToD-DC-Kor/kor-patch#17]
**번역 오류에 대한 설명**
#15 이슈로 제보받은 미번역 문자열

**재현 방법**
N/A

**스크린샷**
![20240901_030359](https://github.com/user-attachments/assets/943e2295-802e-454f-8856-a6cd84b66254)

**실행 환경:**
 - 패치 버전: v0.4.1
 - PCSX2 버전:

**추가 정보**
~~어디서 추출되지 않았는지 확인하기 위해 상황 재현 가능한 세이브와 재현 방법이 필요함~~

SLPS 번역 문자열 재배치 필요

**Comment by kexplo** [comment]
SLPS에 똑같이 생긴 문자열이 있지만, 놓친 레퍼런스가 있는지 확인 필요함.

`[TAG_007]「[TAG_015]」がありましたが[LINE]\nいっぱいでこれ以上持てません。[END]`

**Comment by nevmind** [comment]
[TAG_007]「[TAG_015]」가 있었지만 [LINE]\n가득 차서 더 이상 가질 수 없습니다。[END]
