### ISSUE TITLE
전투시 메뉴 그래픽UI 

### ISSUE THREAD

**Issue by dj5927** [ToD-DC-Kor/kor-patch#18]
**번역 오류에 대한 설명**
간결하고 명료하게 어떤 문제인지 설명해주세요.

**재현 방법**
재현 방법이 명확하고 작업자가 재현해서 살펴봐야 하는 문제라면, 문제를 재현할 수 있는 재현 방법을 적어주세요.
1. 첨부한 세이브 파일 로드
2. 바로 앞의 NPC 말걸기
3. ...

**스크린샷**
가능하다면 도움이 되는 스크린샷을 첨부해주세요. 번역 오류는 스크린샷이 크게 도움 됩니다.

**실행 환경:**
 - 패치 버전:  0.4.2
 - PCSX2 버전: 2.0.2

**추가 정보**

그래픽 100%라고 표기하셔서 못보신부분인듯하여 제보합니다.

전투시 메뉴 호출시 가운데
스킬
장비
작전
아이템
부분입니다.

[
![20240901_210159](https://github.com/user-attachments/assets/2106b83c-6c3f-40c9-abfc-12a21d3dd4d1)
![20240901_210155](https://github.com/user-attachments/assets/2596dafc-ccbb-4d8d-a32d-efa76d168b8a)
](url)

**Comment by kexplo** [comment]
진행도를 헷갈리게 적어놨군요. 전투 쪽 UI는 아직 작업 진행 전이 맞습니다.
진행도 수정해두겠습니다.
