### ISSUE TITLE
체리크에서 노이슈타트로 출항시 회상 장면에서 게임 프리징

### ISSUE THREAD

**Issue by lufi-yuni** [ToD-DC-Kor/kor-patch#2]
**버그에 대한 설명**
항구 도시 체리크에서 노이슈타트로 출항할 때 배에서 필리아가 바티스타에 대해 회상하는 도중 프리징 발생 후 멈춤

**재현 방법**
첨부한 세이브 파일 로드 - 마을 우측 항구로 향한 후 승선 - 배 안에서 프리징

**기대 결과**
버그가 없을 경우 원래 기대되는 결과를 적어주세요.

**스크린샷**
가능하다면 도움이 되는 스크린샷을 첨부해주세요

**실행 환경:**
 - 패치 버전: 0.1.0
 - 실행 기기(또는 에뮬레이터): pcsx2 
 - 실행 기기(또는 에뮬레이터)의 버전: 2.0.2 stable
[Mcd001.zip](https://github.com/user-attachments/files/16649065/Mcd001.zip)

**Comment by kexplo** [comment]
해당 번역 파일에 문제가 있나보네요. 해당 부분만 번역을 제거하면 프리징 현상이 없어집니다.

![Tales of Destiny  Director's Cut _SLPS-25842_20240819003116](https://github.com/user-attachments/assets/e61224fc-9e3f-4b9b-ad2e-70b7d7761145)

문제 발생 부분: 13874_32

https://github.com/ToD-DC-Kor/kor-patch/blob/b43030f532ff6cec84c2f668dafe2951ac7afc43/translations/RSCE/13874_32.txt#L252-L261

정확히 파일의 어느 부분이 문제인지 확인에는 시간이 더 필요합니다.

일단 문제 발생 부분만 제거한 패치를 따로 드립니다. 해당 장면 이후 멈추지 않고 진행하는 것 확인 했습니다.

[patch.zip](https://github.com/user-attachments/files/16649531/patch.zip)

**Comment by kexplo** [comment]
https://github.com/ToD-DC-Kor/kor-patch/releases/tag/v0.1.1

원인 찾아서 수정 후 버그 픽스로 배포 됐습니다.

![Tales of Destiny  Director's Cut _SLPS-25842_20240820002723](https://github.com/user-attachments/assets/0809008e-64d5-418b-b3c0-701603e01dd6)
