### ISSUE TITLE
첼시 미니게임

### ISSUE THREAD

**Issue by kexplo** [ToD-DC-Kor/kor-patch#22]
## 설명

첼시 미니게임 그래픽

정확한 재현 조건에 필요한 세이브 파일이 필요함

유튜브를 돌아다니며 찾은 영문 번역판 그래픽

![image](https://github.com/user-attachments/assets/f08828ed-9137-48a5-908c-628172e25b38)

## 그래픽 에셋

첫번째 줄:

    とくてん (Tokuten) - 특전
    はじめる (Hajimeru) - 시작하기
    かがわ (Kagawa) - 카가와
    ひろかず (Hirokazu) - 히로카즈

두번째 줄:

    おしまい (Oshimai) - 끝내기
    あそびかた (Asobikata) - 조작 방법
    まつい (Matsui) - 마츠이
    まいか (Maika) - 마이카

중앙 (초록색 텍스트):

    ウィアードショット (Weird Shot) - 이상한 샷

하단 텍스트:

    たむら (Tamura) - 타무라
    ひろし (Hiroshi) - 히로시
    たなか (Tanaka) - 타나카
    よしまさ (Yoshimasa) - 요시마사

'특전'을 영문판에서는 'High Scores'로 번역했던데, 저 메뉴를 눌렀을 때 뭐가 나오는지 정확히 알면 번역에 도움이 될 것 같다.

"카가와, 히로카즈, 마츠이, 마이카, 타무라, 히로시, 타나카, 요시마사"는 사람 이름처럼 보인다. 이름 표기를 존중해서 번역하지 않고 그대로 두거나, 그대로 음역해야 할 듯?

![01430_0000dout](https://github.com/user-attachments/assets/7e64d095-fade-4e83-9a42-c5ab48c7c454)

**Comment by Sap1in9** [comment]
세이브 파일 : [ToD_DC_001_Wired_Shot.zip](https://github.com/user-attachments/files/16986904/ToD_DC_001_Wired_Shot.zip)

중단세이브 불러온 후, 앞에 있는 기술자와 대화

**Comment by kexplo** [comment]
![Tales of Destiny  Director's Cut _SLPS-25842_20240914153908](https://github.com/user-attachments/assets/5701d76e-b689-41aa-92e9-d824c1cb62cf)

잘 나오는데, 명칭이 이대로 괜찮은가하는 고민은 여전히 있네요

**Comment by kexplo** [comment]
![Image](https://github.com/user-attachments/assets/710521cf-4d20-4a53-989f-e5971531d267)

다른 명칭으로 리테이크
