### ISSUE TITLE
0.4.2 패치후 처음부터 필리아 동료후 소디언 얻는 부분까지 번역오류

### ISSUE THREAD

**Issue by dj5927** [ToD-DC-Kor/kor-patch#25]
**번역 오류에 대한 설명**
간결하고 명료하게 어떤 문제인지 설명해주세요.

**재현 방법**
재현 방법이 명확하고 작업자가 재현해서 살펴봐야 하는 문제라면, 문제를 재현할 수 있는 재현 방법을 적어주세요.
1. 첨부한 세이브 파일 로드
2. 바로 앞의 NPC 말걸기
3. ...

**스크린샷**
가능하다면 도움이 되는 스크린샷을 첨부해주세요. 번역 오류는 스크린샷이 크게 도움 됩니다.

**실행 환경:**
 - 패치 버전:  0.4.2
 - PCSX2 버전: 2.0.2

**추가 정보**
0.4.2 패치후 처음부터 시작하여 미번역부분과 일어섞여나오는 부분 32곳입니다.
몇개 사진못찍고 놓치긴 했는데 거의 대부분 잡았다고 생각합니다.

모든 npc 2번이상 대화 확인
모든 스킷대화 확인
했습니다.

용량이 커서 구드 링크로 드립니다.

https://drive.google.com/file/d/1UFQ-VyncnVM69yYtyepdKUUo1rKQgoUk/view?usp=sharing

**Comment by kexplo** [comment]
오, 고맙습니다. 굉장히 많은 양이네요. 👍 
직접 플레이 테스트까지 해주시다니 대단합니다.
제보해주신 부분은 따로 확인할게요.

혹시 텍스트 검수나 교정 참여에 관심 없으신가요?

검수에 관심이 있으신 경우에는 저장소를 다운로드 받아서 VS Code로 열어서 문제가 되는 문자열을 검색해서 알려주시면 스크린샷보다 더 간편하실거라 생각합니다.

![image](https://github.com/user-attachments/assets/96395d82-bfc7-4ca2-bfbf-52aa75756596)

![image](https://github.com/user-attachments/assets/239e0c09-4fe8-4e0f-9e66-0f5866b9c793)

(위 스크린샷과 같은 경우에는 `13721_77.txt의 805 라인`으로 리포트 주시면 됩니다)

번역이나 문장 표현 수정 등 교정에 관심이 있으신 경우는, 직접 수정하셔서 변경점을 보내주실 수 있습니다.

**Comment by dj5927** [comment]
다음번 제보시에 한번 해보겠습니다~
항상 감사합니다.

**Comment by dj5927** [comment]
스킷대화는 VSCODE에서 검색이 안되나요?

**Comment by kexplo** [comment]
> 스킷대화는 VSCODE에서 검색이 안되나요?

https://github.com/ToD-DC-Kor/kor-patch/blob/228d6d847527ca153b287fb0524a5bf2750ab881/translations/PAK1_RSCE/15603_0000.txt#L7-L21

검색 됩니다. 다만, 특수 문자가 있거나 줄바꿈이 있을 경우 문자열 매칭이 안 될 수도 있으니 더 짧은 단위로 검색해보세요.

**Comment by dj5927** [comment]
> > 스킷대화는 VSCODE에서 검색이 안 됩니까?
> 
> https://github.com/ToD-DC-Kor/kor-patch/blob/228d6d847527ca153b287fb0524a5bf2750ab881/translations/PAK1_RSCE/15603_0000.txt#L7-L21
> 
> 검색하세요. 활동적인 캐릭터가 있을 경우 바꿈이 있을 경우 문자열 일치가 가능하며 더 단순한 기본으로 검색할 수 있습니다. 또한, 특이한 특징은 코드( `<Stahn>`)로 표현하기 때문에 의미해야 합니다. 예시로 코팅된 15603_0000.txt의 12번 줄을 참고하세요.

네 이름만으로 검색해서 안나왔던거네요~
