### ISSUE TITLE
dc 헬레오스 컨베이어 넓은방에서 좌측방 들어갈 시 팅기는 버그있습니다.

### ISSUE THREAD

**Issue by grraa24** [ToD-DC-Kor/kor-patch#27]
**버그에 대한 설명**
간결하고 명료하게 어떤 문제인지 설명해주세요.

**재현 방법**
재현 방법이 명확하다면, 문제를 재현할 수 있는 메모리 카드 파일과, 재현 방법을 적어주세요. ('상태 저장' 파일은 버그 재현에 사용할 수 없습니다. 메모리 카드 파일로 첨부해주세요)

세이브 파일을 로드한 시점부터 문제가 발생하는 곳까지 도달하는 재현 방법을 적어주세요. 모든 던전과 맵의 지도를 외우고 있지 못하기 때문에, 자세히 설명해 주셔야 합니다.

예시)

1. 첨부한 세이브 파일 로드
2. 오른쪽 문으로 나가서, 건물 바로 앞의 NPC 말걸기
3. 등등...

**기대 결과**
버그가 없을 경우 원래 기대되는 결과를 적어주세요.

**스크린샷**
가능하다면 도움이 되는 스크린샷을 첨부해주세요

**실행 환경:**
 - 패치 버전: 
 - PCSX2 버전: x

**체크 리스트**
- [x] 해당하는 항목을 'x' 체크해주세요
- [ ] 한국어 패치 되지 않은 버전에서도 똑같이 문제가 발생합니다
- [x ] 한국어 패치 된 버전에서만 문제가 발생합니다
- [x ] v0.2.1 버전 이후에 작성된 세이브 파일로 진행했습니다
- [ ] 최신 한국어 패치 버전을 사용했습니다
0.31v 패치버전 
dc 스탄사이드 천상 헬레오스맵 컨베이어 넓은방에서 좌측방 들어갈 시 팅기는 버그있습니다.

**Comment by kexplo** [comment]
패치 버전이 몇 인가요?
정확히 어떤 상황인가요?
스크린샷은 없나요?
https://github.com/ToD-DC-Kor/kor-patch/issues/24 랑 같은 이슈인가요?
https://github.com/ToD-DC-Kor/kor-patch/issues/24#issuecomment-2325086350 이 임시 패치를 사용했을 때 문제가 재현 되나요?

**Comment by lkk9981** [comment]
051 버전으로 테스트 해보세요. 저도 몇일전 비슷한 증상으로 제보 드렸는데, 051버전 업뎃뒤 확인해보니 잘 되네요.
바빠서 확인도 못했는데 그 사이에 수정을 해주실줄이야.. 피드백이 엄청 빠르시네요.

**Comment by asdwewe34** [comment]
패치하는방법은 나와있지않네염.. 직접 찾아봐야하나염..?

**Comment by showa273** [comment]
0.51 로 패치하는법좀알려주실수있나요 도저히해도방법을모르겠네요
