### ISSUE TITLE
몇가지 번역 오류입니다.

### ISSUE THREAD

**Issue by dj5927** [ToD-DC-Kor/kor-patch#29]
**번역 오류에 대한 설명**
간결하고 명료하게 어떤 문제인지 설명해주세요.

**스크린샷**

텍스트 오류 제보 가이드를 따르지 못했다면, 가능하다면 도움이 되는 스크린샷을 첨부해주세요. 번역 오류는 스크린샷이 크게 도움 됩니다.

**재현 방법**
번역 오류가 단순하지 않을 경우, 재현해서 고칠 수 있도록 재현 할 수 있는 세이브 파일과 재현 방법을 적어주세요.

재현 방법 예시)

1. 첨부한 세이브 파일 로드
2. 1시 방향 출구로 이동
3. 가장 가까운 NPC와 말 걸기
4. 등등

**실행 환경:**
 - 패치 버전:  0.5.1
 - PCSX2 버전: 2.0.2

**추가 정보**

상자에서 아이템 획득시 아이템 설명이 4줄이 되면 글자 겹칩이 발생합니다.
3줄로 수정해야 할듯합니다.

그리고 notice 부분에 를2 노 얻었습니다.  < 이부분도 수정이 필요해보입니다.

이부분은 vs code에서 검색해서 찾을수가 없어서 제보드립니다.

![KakaoTalk_20240904_132257461](https://github.com/user-attachments/assets/f5bba7b7-4b34-46bb-8a68-9e983bfe6894)
![KakaoTalk_20240904_132257461_01](https://github.com/user-attachments/assets/ff333ef5-e777-4ad4-a10b-9d870c7d3e96)

여관에서 숙박시 갈드 표기 오류...

실제 100갈드 인데 10010 갈드입니다만.
이라고 표기 됩니다.

대사검색해보니 10 갈드입니다만. << 이라는 대사가 5개정도 있던데 저 대화에서 10을 지우면 되는건지
확실치 않아서 이슈로 제보 합니다.

![KakaoTalk_20240904_132257461_02](https://github.com/user-attachments/assets/4174e103-fa16-4809-aef3-775fc3d3adba)

**Comment by kexplo** [comment]
아이템 문자열 줄 넘침 문제는, 아이템 문자열을 다시 손보면서 없어질 것으로 기대합니다.

하단의 여관에서 묶을 때 '100' 문자열이 덧붙는 현상은 v0.7.0이후로도 재현되는지 확인해주세요. 제가 가진 세이브에서는 재현되지 않네요.
