### ISSUE TITLE
리라이즈 튜톨리얼 끝낸후 마을 나가서 첫전투시 프리징

### ISSUE THREAD

**Issue by dj5927** [ToD-DC-Kor/kor-patch#3]
**버그에 대한 설명**
간결하고 명료하게 어떤 문제인지 설명해주세요.

**재현 방법**
재현 방법이 명확하다면, 문제를 재현할 수 있는 재현 방법을 적어주세요.
1. 첨부한 상태저장1번 세이브 파일 로드 
2. 필드에서 적전투 돌입
3. 버버벅 거리며 프리징 걸림
4. 메뉴에서 파티 진입해도 멈춤
(리라이즈 튜톨전까지는 문제 없었음)

[SLPS-25842 (5F9C9888).01.zip](https://github.com/user-attachments/files/16672097/SLPS-25842.5F9C9888.01.zip)

[Mcd001.zip](https://github.com/user-attachments/files/16675257/Mcd001.zip)

위에껀  일반 세이브 파일입니다.

1. 1번세이브 로드후 여관에서 나오면 리라이즈 설명 이벤트가 시작됩니다.
2. 이벤트 끝난후 필드로 나가지면 전투 돌입시 프리징됩니다.
3. 메뉴호출후 파티에 들어가면 블랙스크린으로 프리징됩니다.

리라이즈 이벤트 전에는 문제 없는거보면
리라이즈 부분에 뭔가 연관된 문제가 아닐까 예상합니다.

**실행 환경:**
 - 패치 버전:  0.2.0
 - 실행 기기(또는 에뮬레이터):  PCSX2 V2.0.2
 - 실행 기기(또는 에뮬레이터)의 버전:

**Comment by dj5927** [comment]
> 제보는 감사한데 에뮬레이터 강제 세이브는 에뮬레이터의 버전이 다르면 호환이 안되는 경우가 잦습니다. 작업자 분에게 제보할 때 메모리 카드에 세이브 된걸로 제보하시는게 좋을거에요

네 이따가 집에가서 바로직전 세이브 있으니 추가하겠습니다.

**Comment by dj5927** [comment]
> @dos1881 답변해주셔서 고맙습니다. 👍
> 
> @dj5927 전달주신 세이브파일의 1번 슬롯은 원인은 모르겠지만 데이터가 망가진 상태로 저장된 것 같습니다. 패치가 되지 않은 환경에서도 똑같은 문제로 프리징이 납니다. 다행히 그보다 조금 앞 시점의 세이브를 2번 슬롯에 해주셔서 리라이즈 튜토리얼까지 진행해봤는데, v0.2.0 패치 환경에서 2번 슬롯부터 진행할 경우에는 프리징 현상이 없습니다. 아마도 그 사이에 행동하신 무언가가 원인이었을 것 같은데, 그 과정이 무엇이었는지 알아내기가 어려울 것 같습니다.
> 
> 아래 첨부한 세이브는 2번 슬롯 세이브 시점부터 진행해서 리라이즈 튜토리얼 이벤트 직전에 **1번 슬롯**에 저장한 세이브입니다. 1번 슬롯을 로드하셔서 진행하시면 프리징 없이 플레이 되실 겁니다.
> 
> [Mcd001.zip](https://github.com/user-attachments/files/16677473/Mcd001.zip)
> 
> 추후 재현조건을 알아내면 원인 분석을 시도해 볼 수 있을 것 같습니다. 제보 고맙습니다.

확인해주셔서 감사합니다.
그렇지 않아도 저도 원본롬으로 진행해봤더니 동일 증상이 나오더라구요...
고급설정에서 tbl오류시 게임일시정지 를 켜놓고 확인해보니
메뉴에서 파티로 진입시 총 60가지 오류가 발생하더라구요....
저 tbl이라는것이 저는 뭔지 잘 모르겠지만요...

**Comment by kexplo** [comment]
> > @dos1881 답변해주셔서 고맙습니다. 👍
> > @dj5927 전달주신 세이브파일의 1번 슬롯은 원인은 모르겠지만 데이터가 망가진 상태로 저장된 것 같습니다. 패치가 되지 않은 환경에서도 똑같은 문제로 프리징이 납니다. 다행히 그보다 조금 앞 시점의 세이브를 2번 슬롯에 해주셔서 리라이즈 튜토리얼까지 진행해봤는데, v0.2.0 패치 환경에서 2번 슬롯부터 진행할 경우에는 프리징 현상이 없습니다. 아마도 그 사이에 행동하신 무언가가 원인이었을 것 같은데, 그 과정이 무엇이었는지 알아내기가 어려울 것 같습니다.
> > 아래 첨부한 세이브는 2번 슬롯 세이브 시점부터 진행해서 리라이즈 튜토리얼 이벤트 직전에 **1번 슬롯**에 저장한 세이브입니다. 1번 슬롯을 로드하셔서 진행하시면 프리징 없이 플레이 되실 겁니다.
> > [Mcd001.zip](https://github.com/user-attachments/files/16677473/Mcd001.zip)
> > 추후 재현조건을 알아내면 원인 분석을 시도해 볼 수 있을 것 같습니다. 제보 고맙습니다.
> 
> 확인해주셔서 감사합니다. 그렇지 않아도 저도 원본롬으로 진행해봤더니 동일 증상이 나오더라구요... 고급설정에서 tbl오류시 게임일시정지 를 켜놓고 확인해보니 메뉴에서 파티로 진입시 총 60가지 오류가 발생하더라구요.... 저 tbl이라는것이 저는 뭔지 잘 모르겠지만요...

TBL 오류는 잘못된 메모리 참조라고 보시면 대충 맞습니다. 해당 세이브에서 진행할 경우에만 발생하는 것을 보니, 저장시점에 잘못 연산된 데이터가 딸려 들어갔을 가능성이 떠오르는데, 아쉽지만 재현 스탭을 알 수 없어서 정확한 원인을 찾을 수 없네요.

**Comment by dj5927** [comment]
> > > @dos1881 답변해주셔서 고맙습니다. 👍
> > > @dj5927 전달주신 세이브파일의 1번 슬롯은 원인은 모르겠지만 데이터가 망가진 상태로 저장된 것 같습니다. 패치가 되지 않은 환경에서도 똑같은 문제로 프리징이 납니다. 다행히 그보다 조금 앞 시점의 세이브를 2번 슬롯에 해주셔서 리라이즈 튜토리얼까지 진행해봤는데, v0.2.0 패치 환경에서 2번 슬롯부터 진행할 경우에는 프리징 현상이 없습니다. 아마도 그 사이에 행동하신 무언가가 원인이었을 것 같은데, 그 과정이 무엇이었는지 알아내기가 어려울 것 같습니다.
> > > 아래 첨부한 세이브는 2번 슬롯 세이브 시점부터 진행해서 리라이즈 튜토리얼 이벤트 직전에 **1번 슬롯**에 저장한 세이브입니다. 1번 슬롯을 로드하셔서 진행하시면 프리징 없이 플레이 되실 겁니다.
> > > [Mcd001.zip](https://github.com/user-attachments/files/16677473/Mcd001.zip)
> > > 추후 재현조건을 알아내면 원인 분석을 시도해 볼 수 있을 것 같습니다. 제보 고맙습니다.
> > 
> > 
> > 확인해주셔서 감사합니다. 그렇지 않아도 저도 원본롬으로 진행해봤더니 동일 증상이 나오더라구요... 고급설정에서 tbl오류시 게임일시정지 를 켜놓고 확인해보니 메뉴에서 파티로 진입시 총 60가지 오류가 발생하더라구요.... 저 tbl이라는것이 저는 뭔지 잘 모르겠지만요...
> 
> TBL 오류는 잘못된 메모리 참조라고 보시면 대충 맞습니다. 해당 세이브에서 진행할 경우에만 발생하는 것을 보니, 저장시점에 잘못 연산된 데이터가 딸려 들어갔을 가능성이 떠오르는데, 아쉽지만 재현 스탭을 알 수 없어서 정확한 원인을 찾을 수 없네요.



커뮤니티에 보면 전투진입시 프리징 걸린다는 얘기들이 쫌 있긴합니다.
그 구간이 다들 다른거보면.. 에뮬자체문제인건지.. 잘 모르겠네요..
어느분은 첫 필드 나간후 전투시 프리징 걸린다하시고
또 어느분은 신전에서 나온후 전투시 걸린다하고..

원인 찾기가 쉽지 않아보이긴합니다..
