### ISSUE TITLE
[번역 오류 제보]: 번역오류 구간입니다.

### ISSUE THREAD

**Issue by dj5927** [ToD-DC-Kor/kor-patch#32]
### 번역 오류에 대한 설명

글자 깨짐

### 패치 버전

0.5.1

### 추가 정보

제가 수정하면 안되는 부분인듯하여 제보로 합니다.

전투시 스킬오류부분 (적스킬은 아직 미번역인지 모르겠습니다.)
![KakaoTalk_20240905_004928230](https://github.com/user-attachments/assets/87b2e2de-09ad-4293-b107-aadd27167245)
![KakaoTalk_20240905_004928230_01](https://github.com/user-attachments/assets/474b8d26-0059-436b-846c-70f3c73ccf73)
![KakaoTalk_20240905_004928230_02](https://github.com/user-attachments/assets/bb0feef4-20b0-485a-a32c-b5effb76a45d)
![KakaoTalk_20240905_004928230_03](https://github.com/user-attachments/assets/da6f0709-8c73-4312-a333-beb4e54b0f02)
![KakaoTalk_20240905_004928230_04](https://github.com/user-attachments/assets/25599085-e798-4d9d-bebd-11bc6d89ccee)
![KakaoTalk_20240905_004928230_05](https://github.com/user-attachments/assets/824db1b3-9e4d-45d3-8591-097a7cdb30d5)

대사오류부분인데.. vc코드에서 뭔가 이상해서 제보로 합니다.

![KakaoTalk_20240905_004928230_06](https://github.com/user-attachments/assets/5b0bb139-83f5-4144-99a3-6a88c34fd1b2)
![KakaoTalk_20240905_004928230_07](https://github.com/user-attachments/assets/7f39b8d5-d273-4c2a-9610-4b35f20c6b37)

**Comment by kexplo** [comment]
스킬 쪽은 분석이 덜 되어서 번역이 오락가락 할 수 있습니다.

대사 쪽은 이전에 보고해주신 것과 합쳐서 일괄로 처리할게요. 👍

**Comment by kexplo** [comment]
https://github.com/ToD-DC-Kor/kor-patch/commit/6c7478d80ffdf3e4749d44833ff7ca51ca0b0c20 스킬 쪽 제외하고 대사 2건 처리 완료
