### ISSUE TITLE
[번역 오류 제보]: 이미지와 번역 오류입니다.

### ISSUE THREAD

**Issue by dos1881** [ToD-DC-Kor/kor-patch#33]
### 번역 오류에 대한 설명

밑에 분 세이브 파일로 확인 중 이미지 오류 및 번역 오류 몇 가지가 보이기에 제보합니다.

![문장 길이 1](https://github.com/user-attachments/assets/09537093-db32-45b0-bcbe-431420d34ba6)
![문장 길이 2](https://github.com/user-attachments/assets/3cf49fc6-8f56-4c96-9c3b-6243acd69068)
![라디슬로우 1](https://github.com/user-attachments/assets/0766d974-c33a-4347-bd6c-d2e1077567b5)
![라디슬로우 2](https://github.com/user-attachments/assets/48ffd654-c966-46f5-bdf2-67d6321c15be)

뿔나팔 같은 경우 문장 길이 문제 같은데 위 오류들은 vscode를 통해 검색해도 나오지가 않더군요.

![번역 1](https://github.com/user-attachments/assets/776d74ce-2734-42a1-978c-29fc667d2365)
13891_109

![번역 2](https://github.com/user-attachments/assets/de1223de-44f0-4fc3-9541-b8a14054ac7a)
15936_0000 

고생에 감사드립니다.

### 패치 버전

0.5.1

**Comment by kexplo** [comment]
대화 전체를 더 자연스럽게 번역한 [v0.7.0 버전](https://github.com/ToD-DC-Kor/kor-patch/releases/tag/v0.7.0)이 배포되었습니다.
번거롭겠지만 한 번 더 확인 부탁드리겠습니다.
