### ISSUE TITLE
[텍스트 교정]: 리온을 '도련님'대신 '아가씨' 등으로 잘못 지칭

### ISSUE THREAD

**Issue by kk950215** [ToD-DC-Kor/kor-patch#34]
### 검수 범위

- [ ] 대화가 발생하는 모든 오브젝트(NPC 등)와 대화를 시도
- [ ] 모든 활성화된 스킷을 확인
- [X] 번역 퀄리티 (잘못된 번역, 말투 등)
- [X] 텍스트 교정 (줄바꿈, 띄어쓰기, 깨진 문자열, 미번역 항목 탐색)

### 검수 구간 설명

일단 플레이하는대로 보고할께요. 리온을 칭할때. "아가씨"라거나 다른 말로 잘못부르는데. 도련님이라고 바꾸는게 좋겟네요 

### 특이사항

당장 플레이하고있는 구간까지는 시스템문구랑 전투팁 번역이 안되있는게 신경쓰이는것 말고는 없을거같네요. 정말 플레이하는데 문제가 안느껴집니다. 

### 패치 버전

0.4.2

**Comment by dos1881** [comment]
도련님이라는 봇짱 호칭이 아가씨로 번역된걸로 보입니다, 아가씨라는 단어가 게임 내 66개 파일에 136번 쓰이는걸로 나오는데
범용적으로 쓰이는 단어라 대사 스크립트만 봐서는 틀린건지 알수가 없고 일괄로 변경하면 또다른 오역이 나올수가 있습니다.
이런 경우는 해당 단어가 포함된 대사가 나오는 구간의 스크린 샷이 필요합니다.
여유가 되신다면 게임을 다시 로드하셔서 스크린샷을 첨부해주시길 바랍니다 에뮬레이터 2.0 이상에서 스샷 단축키는
기본적으로 F8로 설정되어 있고 snaps폴더에 저장됩니다.
추가로 패치 버전은 가급적이면 최신으로 유지해서 제보해 주셔야 작업하는 분에게 도움이 됩니다.

**Comment by Myounghan** [comment]
'거기 너'가 어울릴 것 같은데 '저기 너'로 되어 있어서 신고합니다.
![Tales of Destiny  Director's Cut _SLPS-25842_20240905172844](https://github.com/user-attachments/assets/8a7bb137-b892-47b5-afae-546b2599907b)

**Comment by dos1881** [comment]
ㄴ14219_48 이군요.

제보하시는 분들은 이 링크를 참조해서 https://github.com/ToD-DC-Kor/kor-patch/issues/25#issuecomment-2324956280

파일 넘버를 작업자 분께 알려주시면 작업에 보탬이 되실 듯합니다.

**Comment by kexplo** [comment]
@dos1881 안내 고맙습니다.

'도련님' 호칭 문제는 일괄 교정하기 애매하므로, 문제되는 케이스를 개별로 찾아서 교정해야 할 것 같습니다.

**Comment by Myounghan** [comment]
ㄴ14219_48 은 "저기, 너"이고
ㄴ13570_117 이 "저기 너!"인 것 같습니다.
확인 좀 부탁드려요.

**Comment by kexplo** [comment]
대화 전체를 더 자연스럽게 번역한 [v0.7.0 버전](https://github.com/ToD-DC-Kor/kor-patch/releases/tag/v0.7.0)이 배포되었습니다.

'도련님' 호칭 문제는 대부분 해결된 것으로 보이는데, 혹시 이슈가 남아있는 부분이 있는지 확인 부탁드립니다.
스크린샷의 '저기 너'는 '거기 너'로 번역되었습니다.
