### ISSUE TITLE
[버그 제보]: 스킷 배경 깨짐

### ISSUE THREAD

**Issue by kexplo** [ToD-DC-Kor/kor-patch#343]
### 버그에 대한 설명

스킷 배경 깨짐

### 재현 방법

(디스코드 제보)
https://discord.com/channels/1281616790958637120/1281626933695610890/1283005378396684299
세이브슬롯 39 칼비올라에서 스크린챗 실행시 배경깨짐

### 패치 버전

v0.6.0

### PCSX2 버전

-

### 체크리스트

- [ ] 한국어 패치 되지 않은 버전에서도 문제가 발생합니다
- [ ] 한국어 패치 된 버전에서만 문제가 발생합니다
- [ ] v0.2.1 패치 버전 이후에 작성된 세이브 파일로 진행했습니다
- [ ] 최신 한국어 패치 버전을 사용했습니다

**Comment by Sap1in9** [comment]
안드로이드 에뮬레이터 NetherSX2(v1.5-4248) 구동시 배경 깨짐
PC 에뮬레이터 PCSX2(v2.0.2) 구동시 정상적으로 나옵니다.
![image](https://github.com/user-attachments/assets/74ecf46e-e417-446a-a15d-92a8633bfeb2)

**Comment by kexplo** [comment]
에뮬레이터 호환성 문제였겠네요. PCSX2에서는 정상으로 나오니 문제 없는 것으로 보겠습니다. @Sap1in9 님 확인 감사해요.
