### ISSUE TITLE
[텍스트 교정]: 부하가 함장에게 반말

### ISSUE THREAD

**Issue by Myounghan** [ToD-DC-Kor/kor-patch#35]
### 검수 범위

- [ ] 대화가 발생하는 모든 오브젝트(NPC 등)와 대화를 시도
- [ ] 모든 활성화된 스킷을 확인
- [X] 번역 퀄리티 (잘못된 번역, 말투 등)
- [ ] 텍스트 교정 (줄바꿈, 띄어쓰기, 깨진 문자열, 미번역 항목 탐색)

### 검수 구간 설명

초반에 함장에게 부하가 말하는 장면 인데 데스(입니다)로 존댓말을 하는데 번역은 그냥 반말로 되어 있습니다.
![Tales of Destiny  Director's Cut _SLPS-25842_20240905170445](https://github.com/user-attachments/assets/7433f244-17be-4e08-a464-045d06b81d61)

### 패치 버전

0.5.1

**Comment by dos1881** [comment]
ㄴ13558_61 되겠습니다.

**Comment by Myounghan** [comment]
ㄴ13582_61
"괜찮아 보이는군"이 더 나은 번역인 것 같습니다.

![Tales of Destiny  Director's Cut _SLPS-25842_20240905175414](https://github.com/user-attachments/assets/ba57e53e-8861-4ed0-8856-fe812f83b858)

**Comment by Myounghan** [comment]
ㄴ13583_76
"흔적은 없다"가 올바른 표현 같습니다.
![Tales of Destiny  Director's Cut _SLPS-25842_20240905175728](https://github.com/user-attachments/assets/d63933a6-dc92-4490-8c6a-03d172f42711)

**Comment by kexplo** [comment]
대화 전체를 더 자연스럽게 번역한 [v0.7.0 버전](https://github.com/ToD-DC-Kor/kor-patch/releases/tag/v0.7.0)이 배포되었습니다.

말씀하신 문제가 모두 해결된 것으로 보이는데 확인 부탁드립니다.
