### ISSUE TITLE
미번역 문장

### ISSUE THREAD

**Issue by kexplo** [ToD-DC-Kor/kor-patch#37]
https://github.com/ToD-DC-Kor/kor-patch/issues/25 이슈.

![Image](https://github.com/user-attachments/assets/712b475e-1ee0-447a-abe6-2c5d033e3ba9)

"2つ以上のストラップをセットした状態で 寿引のストラップが出現を得たした場合、 その中で割も上にあるものが平等されます。"

![Image](https://github.com/user-attachments/assets/a4822532-1561-4d02-bbea-6bfe17f047ad)

**Comment by dlatod84** [comment]
2つ以上のストラップをセットした状態で 寿引のストラップが出現を得たした場合、その中で割も上にあるものが平等されます。"
"2개 이상의 스트랩을 세트한 상태로 수인의 스트랩이 출현을 얻었을 경우, 그 중에서도 나란히 있는 것이 평등됩니다. "
구글
"2개 이상의 스트랩을 세트한 상태에서 히데키의 스트랩이 출현을 얻은 경우, 그 중에서 할도 위에 있는 것이 평등합니다."
파파고

**Comment by Sap1in9** [comment]
![image](https://github.com/user-attachments/assets/a24b39de-7b53-4a0a-a6a8-150e5e680787)
스노우프리아 우드로우, 첼시 합류 이후 'ひどい' 2번정도 미번역 출력됨
번역기 돌려보니 '너무해' 라고 번역됨.
세이브슬롯 67번 [ToD_DC_001_240912.zip](https://github.com/user-attachments/files/16972303/ToD_DC_001_240912.zip)
재현 : 여관 나가서 남쪽으로 이동 -> 스노우프리아 나가기 -> 이벤트 진행 -> 자동 전투 후 이벤트
