### ISSUE TITLE
번역 오류 NPC 위치 찾기

### ISSUE THREAD

**Issue by kexplo** [ToD-DC-Kor/kor-patch#38]
https://github.com/ToD-DC-Kor/kor-patch/issues/25 이슈.

![Image](https://github.com/user-attachments/assets/5864d59e-cdaa-410a-9fcd-33c09aae6448)

왼쪽의 빈 말풍선 대사가 어느 파일에서 등장하는지 알아내야 함.

**Comment by kexplo** [comment]
@dj5927 님, 혹시 왼쪽 스크린샷의 NPC를 만날 수 있는 세이브파일을 가지고 계신다면, 한국어 패치하지 않은 버전에서 어떤 일본어 대사를 하는지 찍어주실 수 있나요?

**Comment by dj5927** [comment]
> @dj5927 님, 혹시 왼쪽 스크린샷의 NPC를 만날 수 있는 세이브파일을 가지고 계신다면, 한국어 패치하지 않은 버전에서 어떤 일본어 대사를 하는지 찍어주실 수 있나요?

중간중간 세이브 슬롯을 바꿔가면서 저장해서 최대한 가까운곳에서 로드해서 찾아보겠습니다.

저렇게 뜨는 경비병이 두명이였습니다.

**Comment by dj5927** [comment]
![20240907_032353](https://github.com/user-attachments/assets/502cc703-400d-4ab0-a792-393d16f60d5f)
![20240907_032337](https://github.com/user-attachments/assets/adc618e5-0523-434d-a4ec-9a8e1c6601a4)


일판구동으로 이 2곳입니다.

**Comment by dj5927** [comment]
[Mcd001.zip](https://github.com/user-attachments/files/16911813/Mcd001.zip)

필요하실수도 있어서 세이브파일 올려드립니다.
중단세이브 로드하시면 바로앞입니다.

**Comment by kexplo** [comment]
중단 세이브파일 엄청 도움되네요. 👍 

セイングルド兵
こちらは異常ありませんっ!

원문은 13693_41, 13707_35 두 곳에 들어있군요

**Comment by kexplo** [comment]
13695_34

문자열 길이 넘침 현상이군요

![Tales of Destiny  Director's Cut _SLPS-25842_20240908165058](https://github.com/user-attachments/assets/e3006cfe-15ac-42cc-acdb-6775f13751be)

**Comment by kexplo** [comment]
원인 알았으니, 다른 이슈로 추적하고 이 이슈는 닫습니다.
