### ISSUE TITLE
[번역 오류 제보]: 15646_0000 13번 아하,귀신 시험이구나 및 기타등등

### ISSUE THREAD

**Issue by dlatod84** [ToD-DC-Kor/kor-patch#40]
### 번역 오류에 대한 설명

15646_0000 13번 아하,귀신 시험이구나 -> 아하,공포 체험이구나

15635_0000 17번 숲을 잠시 진행해, 막다른 곳 -> 숲을 잠시 지나서, 막다른 곳

15636_0000 8번 숲을 잠시 진행해, 막다른 곳 -> 숲을 잠시 지나서, 막다른 곳

### 패치 버전

0.1

**Comment by kexplo** [comment]
대화 전체를 더 자연스럽게 번역한 [v0.7.0 버전](https://github.com/ToD-DC-Kor/kor-patch/releases/tag/v0.7.0)이 배포되었습니다.

다음과 같이 다시 번역 된 것으로 확인됩니다:

```
그렇구나 담력 시험이구나.
숲을 한참 가다 보면 막다른 곳이 나와
```
