### ISSUE TITLE
[세이브 파일 구함]: 태고의 달인 패러디 미니게임

### ISSUE THREAD

**Issue by kexplo** [ToD-DC-Kor/kor-patch#42]
#19 그래픽 한글화 작업이 정상적으로 적용되는지 테스트하기 위해 필요합니다.

해당 미니게임을 시도할 수 있는 직전의 세이브 파일을 제공해주실 분을 구합니다. 댓글로 첨부해주세요.

**Comment by hoohooha** [comment]
[Mcd001.zip](https://github.com/user-attachments/files/17071446/Mcd001.zip)

**Comment by Sap1in9** [comment]
[ToD_DC_002_Taiko_Drum.zip](https://github.com/user-attachments/files/17071579/ToD_DC_002_Taiko_Drum.zip)

중단세이브 열기 후 기술자와 대화
