### ISSUE TITLE
[세이브 파일 구함]: 첼시 미니게임

### ISSUE THREAD

**Issue by kexplo** [ToD-DC-Kor/kor-patch#43]
#22 그래픽 한글화 작업을 테스트하기 위해 필요합니다.

첼시 미니게임을 플레이 할 수 있는 상태의 세이브파일을 구합니다. 댓글로 첨부해주세요.

**Comment by RPG-Nerd** [comment]
혹시 도움이 될까 싶어서 스탄 & 리온 사이드 일판 클리어 세이브 파일 첨부합니다.

[테일즈 오브 데스티니 DC 클리어 세이브.zip](https://github.com/user-attachments/files/16913737/DC.zip)

**Comment by Sap1in9** [comment]
https://github.com/ToD-DC-Kor/kor-patch/issues/22#issuecomment-2347489417
