### ISSUE TITLE
[버그 제보]: 헬리오스 진행불가 버그

### ISSUE THREAD

**Issue by z1x2xc2300** [ToD-DC-Kor/kor-patch#434]
### 버그에 대한 설명

조사하기 상호작용 안됨

### 재현 방법

헬리오스 카드키 입수시 회색카드 입수 과정에서 카드키 등록하는 기계 상호작용 안됨 
패치전 조사하기 뜸 패치후 안됨 진행 불
![KakaoTalk_20240913_084812536_01](https://github.com/user-attachments/assets/f4478857-8d74-4ff0-a708-448a60aa4f6b)
![KakaoTalk_20240913_084812536](https://github.com/user-attachments/assets/76439c0c-53fc-4541-ae3e-83c41d758121)

### 패치 버전

0.7.0

### PCSX2 버전

netherSX2 1.9

### 체크리스트

- [ ] 한국어 패치 되지 않은 버전에서도 문제가 발생합니다
- [X] 한국어 패치 된 버전에서만 문제가 발생합니다
- [X] v0.2.1 패치 버전 이후에 작성된 세이브 파일로 진행했습니다
- [X] 최신 한국어 패치 버전을 사용했습니다

**Comment by kexplo** [comment]
재현 세이브파일 첨부해주세요.

**Comment by Sap1in9** [comment]
[ToD_DC_002_240919.zip](https://github.com/user-attachments/files/17061310/ToD_DC_002_240919.zip)
38번 세이브 불러오기 후 왼쪽으로 진행하시면 됩니다.

**Comment by kexplo** [comment]
14567_112 block 깨짐 이슈.

![image](https://github.com/user-attachments/assets/736e62e5-7150-4ff4-9e73-6aa022c31d8f)

수정했고, 다음 패치에 적용될 예정입니다.
