### ISSUE TITLE
[버그 제보]: 루티 칭호 팅김 버그

### ISSUE THREAD

**Issue by Sap1in9** [ToD-DC-Kor/kor-patch#435]
### 버그에 대한 설명

에뮬레이터 튕김현상

### 재현 방법

세이브파일 : [ToD_DC_002_240913.zip](https://github.com/user-attachments/files/16989182/ToD_DC_002_240913.zip)
재현방법 : 3번 슬롯 불러오기 후 세인가르드 성으로 진입, 음표 말풍선 띄워져있는 병사에 말걸기
![테일즈 오브 데스티니 디렉터즈 컷_SLPS-25842_20240913145530](https://github.com/user-attachments/assets/0a2a8180-c7d1-44ac-831d-a61f915d9e38)
대화 출력 안됨
![테일즈 오브 데스티니 디렉터즈 컷_SLPS-25842_20240913145651](https://github.com/user-attachments/assets/4213dc92-6c0f-40f3-bb90-1d2b92064205)
첫번째 선택지 선택
![테일즈 오브 데스티니 디렉터즈 컷_SLPS-25842_20240913145705](https://github.com/user-attachments/assets/ed92e3fc-61d2-4df6-8789-c92097d5a90d)
이 대사 이후 에뮬레이터 강제종료

![Tales of Destiny  Director's Cut _SLPS-25842_20240913150234](https://github.com/user-attachments/assets/318dfb56-2dbe-44d4-9e76-8fa2313de282)
![Tales of Destiny  Director's Cut _SLPS-25842_20240913150212](https://github.com/user-attachments/assets/90f06853-08d5-4e2c-9b4e-2e98d24f36ca)
원본으로 진행시 버그 없음

### 패치 버전

0.7.0

### PCSX2 버전

2.0.2

### 체크리스트

- [ ] 한국어 패치 되지 않은 버전에서도 문제가 발생합니다
- [X] 한국어 패치 된 버전에서만 문제가 발생합니다
- [X] v0.2.1 패치 버전 이후에 작성된 세이브 파일로 진행했습니다
- [X] 최신 한국어 패치 버전을 사용했습니다

**Comment by kexplo** [comment]
![Image](https://github.com/user-attachments/assets/e9dfa4e0-267d-4bca-a7d5-46838766afcb)

수정되었고, 다음 패치에 적용 예정입니다.
