### ISSUE TITLE
[번역 오류 제보]: NEW GAME 시 텍스트 관련

### ISSUE THREAD

**Issue by Da1eth** [ToD-DC-Kor/kor-patch#437]
### 번역 오류에 대한 설명

"어느 쪽에서 게임을 시작할까요?" 라는 문장이 아무래도 어색하지 않을까 싶어서요
원문과 조금 달라지더라도 "누구 시점에서 게임을 시작할까요?" 가 맞을지도 모른다고 생각합니다.

또, 스탄 쪽의 "오리지널에서 마지막까지 하지 않으신 분은-" 은
"오리지널판을 끝까지 플레이하지 않으신 분은 이쪽부터 플레이할 것을 추천합니다." 가 자연스럽지 않을까 싶고,

리온 쪽의 "뒷이야기"는 원문이 裏の物語인데 이걸 그냥 뒷이야기로 하면 본편의 후일담으로 오인될 여지가 있기 때문에 "숨겨진 이야기입니다" 라던가
아예 문장을 통째로 의역해서 "스탄 시점에서는 볼 수 없는 숨겨진 이야기를 볼 수 있기 때문에-" 로 다음 문장과 잇는 것도 괜찮지 않을까 싶습니다.

### 패치 버전

0.7.0

**Comment by kexplo** [comment]
번역 제안 고맙습니다. 현재 번역은 AI에 의존하고 있기 때문에 원래의 의미를 놓치는 경우가 종종 있습니다.

제보 또는 검수에 기여해 주시면 도움이 많이 됩니다.

제안 주신 "누구 시점에서 게임을 시작할까요?" 문장이 훨씬 더 좋은 것 같은데, 글자 수 제한에 걸려서 전체를 적을 수가 없군요. 기존 번역을 유지하거나 "누구 시점에서 시작할까요?" 정도를 적용해볼 수 있을 것 같습니다.

나머지 제안은 거의 그대로 적용 가능해 보입니다.

![Image](https://github.com/user-attachments/assets/4ed8bae7-6725-4748-a618-c48941823624)
![Image](https://github.com/user-attachments/assets/5888dd2e-ce59-47ba-8b01-af09d605e909)
