### ISSUE TITLE
[버그 제보]: 블랙스크린

### ISSUE THREAD

**Issue by showa273** [ToD-DC-Kor/kor-patch#441]
### 버그에 대한 설명

진입시 블랙스크린

### 재현 방법

후반부 다이로크프트 
![캡처](https://github.com/user-attachments/assets/d12e2548-b55a-4887-9559-14c37d785087)

여기서 12시계단방향으로 들어가면 블랙스크린뜹니다 확인부탁드립니다

### 패치 버전

0.7.0

### PCSX2 버전

v2.1.127

### 체크리스트

- [ ] 한국어 패치 되지 않은 버전에서도 문제가 발생합니다
- [x] 한국어 패치 된 버전에서만 문제가 발생합니다
- [x] v0.2.1 패치 버전 이후에 작성된 세이브 파일로 진행했습니다
- [X] 최신 한국어 패치 버전을 사용했습니다

**Comment by kexplo** [comment]
재현가능한 세이브파일 제공해주세요. 세이브포인트에서 버그 위치까지 거리가 멀면 중단 세이브해서 제공해주세요.

**Comment by showa273** [comment]
세이브파일 어떻게올리죠???

**Comment by kexplo** [comment]
> 세이브파일 어떻게올리죠???

zip으로 압축해서 본문이나 댓글에 드래그하면 올라갑니다

**Comment by showa273** [comment]
[Mcd001.zip](https://github.com/user-attachments/files/17046837/Mcd001.zip)

**Comment by showa273** [comment]
이렇게하면될까요?

**Comment by kexplo** [comment]
네, 세이브 파일은 잘 올려주셨는데. 재현 방법 적어주세요. @showa273 

세이브포인트에서 어디로 가야 재현장소에 도달하나요? 세이브포인트가 멀면 중단 세이브로 저장해서 주세요.

**Comment by kexplo** [comment]
헤매다가 비슷해 보이는 장소에 도달하긴 했는데, 제 경우에는 버그가 재현이 안 되네요.

![Tales of Destiny  Director's Cut _SLPS-25842_20240919021646](https://github.com/user-attachments/assets/065ced27-3915-45c3-a6a0-fbd1632a2389)
![Tales of Destiny  Director's Cut _SLPS-25842_20240919021758](https://github.com/user-attachments/assets/3b8b6158-149b-4c5e-805a-0017bfc7beee)
![Tales of Destiny  Director's Cut _SLPS-25842_20240919021801](https://github.com/user-attachments/assets/cfe4142d-711a-41ba-be04-e3360928f541)

**Comment by kexplo** [comment]
1주일 이상 방치되어, 이슈 종료합니다.
