### ISSUE TITLE
[번역 오류 제보]:  번역 오류입니다.

### ISSUE THREAD

**Issue by zysworld** [ToD-DC-Kor/kor-patch#449]
### 번역 오류에 대한 설명

![gsdx_20240916140655](https://github.com/user-attachments/assets/a1f3b441-9821-48d3-b1b1-2f86513a4f9e)
![gsdx_20240916152744](https://github.com/user-attachments/assets/eb5c80c3-c085-4ab2-aaff-ce6fff576c96)
![gsdx_20240916165828](https://github.com/user-attachments/assets/288781f8-4176-40e5-b4fe-4efa8486bd9f)
![gsdx_20240918164919](https://github.com/user-attachments/assets/fe3aa75e-d47c-437e-9009-ca42372192f5)

### (선택사항) 재현 방법

여전히 큘이라고 나오네요

위에는 어택이 나오고 공격을 설정해보세요라고 나오네요

스킷을 넘기는 부분이 번역이되어 있지 않네요. 

후드라고 나오는 부분은 이전 버전에도 번역이 되지 않은 부분입니다.

### 패치 버전

0.7.0

**Comment by kexplo** [comment]
맨 위는 #51 에서 제보주셨던 건이죠? 아직 미해결 상태입니다.

공격/어택 표기 어긋나는 튜토리얼은 https://github.com/ToD-DC-Kor/kor-patch/pull/444/files 에서 교정되어야 할 것 같네요.

스킷 넘기는 부분은 다음 패치에서 스킷 타이틀 번역 작업되면서 같이 해결됩니다. v0.7.0에는 미포함이에요.

후드라고 된 부분은 #52 에서 제보주셨던 거랑 같은 건인 것 같고 아직 미해결 상태입니다.

**Comment by kexplo** [comment]
기존 제보랑 중복되니까 이 이슈는 닫을게요. 이후 작업 추적은 #51 #52 확인해 주세요.
