### ISSUE TITLE
[번역 오류 제보]: 줄바꿈 필요한 문장

### ISSUE THREAD

**Issue by Sap1in9** [ToD-DC-Kor/kor-patch#450]
### 번역 오류에 대한 설명

![테일즈 오브 데스티니 디렉터즈 컷_SLPS-25842_20240920152757](https://github.com/user-attachments/assets/1dc97107-34c6-4172-8ee1-4b4874a4d228)
![테일즈 오브 데스티니 디렉터즈 컷_SLPS-25842_20240920152801](https://github.com/user-attachments/assets/6d95f158-f0a8-4a1a-88a7-d9323db4d42b)
![테일즈 오브 데스티니 디렉터즈 컷_SLPS-25842_20240920152805](https://github.com/user-attachments/assets/4e1f0b4d-8a1c-454b-903f-77ae87efcfee)
![테일즈 오브 데스티니 디렉터즈 컷_SLPS-25842_20240920152807](https://github.com/user-attachments/assets/57ceebeb-6ef8-41d7-9d22-ef5744fa4120)
![테일즈 오브 데스티니 디렉터즈 컷_SLPS-25842_20240920152820](https://github.com/user-attachments/assets/e1e5bf5a-3665-45f9-829a-b56a9659cae2)

### (선택사항) 재현 방법

[ToD_DC_002_240920.zip](https://github.com/user-attachments/files/17070901/ToD_DC_002_240920.zip)
54번 세이브 불러오기 → 여관 나와서 마을 북쪽으로 이동 → 이벤트

### 패치 버전

0.8.0

**Comment by kexplo** [comment]
https://github.com/ToD-DC-Kor/kor-patch/pull/107 PR에 교정처리 했습니다.
