### ISSUE TITLE
[버그 제보]: 서브이벤트 진행불가

### ISSUE THREAD

**Issue by Sap1in9** [ToD-DC-Kor/kor-patch#453]
### 버그에 대한 설명

아래층이나 테라스로 이동불가

### 버그 재현 방법

![Screenshot_20240922-135021](https://github.com/user-attachments/assets/0fb5e8fb-db6b-454e-8a79-230887f5b9b9)

[ToD_DC_002_240922.zip](https://github.com/user-attachments/files/17088428/ToD_DC_002_240922.zip)
68번 세이브 불러오기 -> 여관 나와서 북쪽으로 -> 조니 집으로 들어가서 2층으로 이동 -> 다른 층이나 테라스로 이동 불가

### 패치 버전

0.8.0

### PCSX2 버전

NetherSX2 v1.5-4248

### 체크리스트

- [ ] 한국어 패치 되지 않은 버전에서도 문제가 발생합니다
- [X] 한국어 패치 된 버전에서만 문제가 발생합니다
- [X] v0.2.1 패치 버전 이후에 작성된 세이브 파일로 진행했습니다
- [X] 최신 한국어 패치 버전을 사용했습니다
- [X] 재현 가능한 세이브 파일을 첨부했습니다

**Comment by kexplo** [comment]
14078_30, 깨진 문자열 블록 문제였네요.

고쳤습니다.
