### ISSUE TITLE
[번역 오류 제보]: 라디슬로우 지역 번역 오류

### ISSUE THREAD

**Issue by KwonHyungGeun** [ToD-DC-Kor/kor-patch#455]
### 번역 오류에 대한 설명

![image](https://github.com/user-attachments/assets/4f1c0de1-37aa-49d6-acfc-c0567f5060d2)

월드맵 진입 후 세계지도 R3버튼 으로 호출시 

라디슬로우 텍스트가 깨짐. 

실제 라디슬로우 접근 하면 좌측 상단 명칭도 

동일하게 깨진 텍스트로 보임.

### (선택사항) 재현 방법

[Mcd001.zip](https://github.com/user-attachments/files/17090143/Mcd001.zip)

디스코드에서 재현이 불가하다고 하시어 제 세이브파일 전달 드립니다.

### 패치 버전

0.8.0 BETA

**Comment by kexplo** [comment]
![Image](https://github.com/user-attachments/assets/cf0dbf6b-502d-4c27-9c3c-b2e94da908b6)
![Image](https://github.com/user-attachments/assets/abe28322-d61a-4d79-96a6-743ee1e57147)

수정완료
