### ISSUE TITLE
[번역 오류 제보]: 필리아 소디언디바이스 레스큐 설명

### ISSUE THREAD

**Issue by nakarydingoo** [ToD-DC-Kor/kor-patch#462]
### 번역 오류에 대한 설명

![핍사](https://github.com/user-attachments/assets/ef37cacb-319b-47ba-b7a3-1576b38c7a91)

### (선택사항) 재현 방법

필리아서 소디언디바이스 LV3 레스큐 설명 핍사 로 표기

### 패치 버전

0.8.0

**Comment by kexplo** [comment]
최신 번역에서는 "빈사 상태에서"로 번역된 것을 확인하여 이슈 종료합니다.
