### ISSUE TITLE
[번역 오류 제보]: 몬스터 도감 UI 미번역

### ISSUE THREAD

**Issue by dj5927** [ToD-DC-Kor/kor-patch#464]
### 번역 오류에 대한 설명

미번역 구간

### (선택사항) 재현 방법

![20240928052431_1](https://github.com/user-attachments/assets/e049fb4b-6e40-4ff9-a096-4c1201488e36)

1번 스샷

69번 세이브 로드후 세계지도 (R3) 사용시 바로뜸
(외각진입후 처음 지도사용시에만 발생)

![20240929062317_1](https://github.com/user-attachments/assets/508f5ada-feb2-41de-9767-20cc81eac88e)

2번 스샷

디피니트전기가 메뉴이름 이미지에는 몬스터도감으로 뜸 그리고 미번역

![20240929062336_1](https://github.com/user-attachments/assets/9cb90de7-1ff4-4b6a-b95e-ecbb5afda5c3)
![20240929062349_1](https://github.com/user-attachments/assets/da4e7a50-75d0-4e2e-801c-7e7417430bf4)

3~4번 스샷

몬스터도감 미번역
줄거리책 미번역

[Mcd001.zip](https://github.com/user-attachments/files/17176646/Mcd001.zip)

### 패치 버전

0.8.0

**Comment by kexplo** [comment]
> 디피니트전기가 메뉴이름 이미지에는 몬스터도감으로 뜸

일본판에서도 원래 몬스터도감이 표시된 것으로 알고 있는데, 확인해봐 주실래요?

**Comment by dj5927** [comment]
> > 디피니트전기가 메뉴이름 이미지에는 몬스터도감으로 뜸
> 
> 일본판에서도 원래 몬스터도감이 표시된 것으로 알고 있는데, 확인해봐 주실래요?

확인해보니 맞습니다. 일판도 몬스터도감으로 뜨네요~

**Comment by kexplo** [comment]
![Image](https://github.com/user-attachments/assets/562d19af-048b-4c82-b7c8-25da6e58b5c2)

첫번째 미번역 문제는 해결됐습니다. 9/30이후 패치버전부터 적용됩니다.

나머지 이슈는 몬스터 도감 쪽이라서 따로 챙길게요

**Comment by kexplo** [comment]
![Image](https://github.com/user-attachments/assets/550cee60-0c2c-4c3e-81ab-9c090e5d2a1e)

몬스터 도감 UI는 v0.8.0 이후 수정됩니다.
