### ISSUE TITLE
[번역 오류 제보]: 스탄 스킬 마신쌍파참 설명

### ISSUE THREAD

**Issue by nakarydingoo** [ToD-DC-Kor/kor-patch#465]
### 번역 오류에 대한 설명

마신쌍파참 스킬 설명 '뜬' 으로 표기
![마신쌍파참](https://github.com/user-attachments/assets/22da6fa0-532c-4ad4-a630-556c643f779f)

### 패치 버전

0.8.0

**Comment by kexplo** [comment]
최신 번역은 "띄우는 효과가 있는 마신검을..."로 번역된 것으로 확인되어 이슈 종료합니다.
