### ISSUE TITLE
[번역 오류 제보]: 라디슬로우 표기 오류

### ISSUE THREAD

**Issue by nakarydingoo** [ToD-DC-Kor/kor-patch#466]
### 번역 오류에 대한 설명

![라디슬로우](https://github.com/user-attachments/assets/73533f90-1099-44af-b8c3-3730678f1ba3)
지상에 있는 라디슬로우 표기 & 설명 번역 오류

### 패치 버전

0.8.0

**Comment by kexplo** [comment]
혹시 스크린샷 위치에서의 세이브파일 제공 가능할까요?
문자열 포인터 오류인 것 같아서 재현되는 상황 만들어 놓고 고쳐야 할 것 같습니다.

**Comment by dj5927** [comment]
> 혹시 스크린샷 위치에서의 세이브파일 제공 가능할까요? 문자열 포인터 오류인 것 같아서 재현되는 상황 만들어 놓고 고쳐야 할 것 같습니다.

https://github.com/ToD-DC-Kor/kor-patch/issues/458#issue-2551965423

이글에 있는것과 같은제보입니다.  제가 올린글에 세이브 첨부되어있습니다.

**Comment by kexplo** [comment]
아 같은 거군요. 그러면 이 이슈는 닫고, #458 이슈에서 이후 진행 업데이트 하겠습니다.
