### ISSUE TITLE
[번역 오류 제보]: 메모리카드 관련 메시지 오류

### ISSUE THREAD

**Issue by Sap1in9** [ToD-DC-Kor/kor-patch#468]
### 번역 오류에 대한 설명

![Tales of Destiny  Director's Cut _SLPS-25842_20240930170056](https://github.com/user-attachments/assets/91be382a-ca43-4bba-abb0-72c93ba1d8b1)

포맷 안된 메모리카드 지정하여 저장메뉴 호출시 예/아니오 메시지 미출력

### (선택사항) 재현 방법

[ToD_DC_003.zip](https://github.com/user-attachments/files/17186279/ToD_DC_003.zip)
게임 로드 후, 에뮬레이터에서 메모리카드 교체 -> 저장
(첨부파일 : 포맷 안된 메모리카드)

### 패치 버전

0.8.0

**Comment by kexplo** [comment]
![Image](https://github.com/user-attachments/assets/e5f53701-aeb6-4277-9bd7-84ecb50156b7)

고쳤습니다. 9/30 이후 패치부터 반영됩니다.
