### ISSUE TITLE
[번역 오류 제보]: 기묘한 샷 미니게임중 미번역 부분

### ISSUE THREAD

**Issue by dj5927** [ToD-DC-Kor/kor-patch#470]
### 번역 오류에 대한 설명

![20241002203259_1](https://github.com/user-attachments/assets/081aff12-2014-4345-8617-f7d812bbc4bc)
![20241002203414_1](https://github.com/user-attachments/assets/aa151e3c-6299-46cb-9dfd-c26b1b294b72)
![20241002210645_1](https://github.com/user-attachments/assets/10a34ad7-9529-4aba-8402-172e59a1196d)

[Mcd001.zip](https://github.com/user-attachments/files/17228862/Mcd001.zip)

중단세이브 로드후 바로 앞 npc와 대화해서 미니게임 진행

하나는 설명보기
두개는 미니게임완료후 나옴
(처음에만 나오고 안나오는걸수도 있어서.. 또 안뜰수도 있습니다.)

### 패치 버전

0.8.0

**Comment by kexplo** [comment]
![Image](https://github.com/user-attachments/assets/222354d5-96f2-4192-bf67-8959dbf2f361)

첨부하신 3가지 스크린샷 문자열 전부 추출 및 초벌 번역 완료
