### ISSUE TITLE
[번역 오류 제보]: 리온 사이드 처음 시작할 때 폰트 출력 문제

### ISSUE THREAD

**Issue by RPG-Nerd** [ToD-DC-Kor/kor-patch#48]
### 번역 오류에 대한 설명

스탄 사이드 세이브가 있는 상태에서 리온 사이드를 처음 시작하면 아무 멘트가 나오지 않지만
스탄 사이드 세이브가 없는 상태에서 리온 사이드를 처음 시작하면 안내 멘트가 나오는데
한글 패치가 적용된 상태에서 폰트 출력이 정상적으로 나오지 않습니다.

![리온 사이드 폰트 원본](https://github.com/user-attachments/assets/cf66d103-1d6d-42d4-8026-53fa912d11af)
![리온 사이드 폰트 문제](https://github.com/user-attachments/assets/25a3edca-c3b8-4812-8d16-5a458fe24528)

### 패치 버전

v0.5.1

### 추가 정보

혹시 도움이 될까 싶어서 스탄 & 리온 사이드 일판 클리어 세이브 파일도 같이 첨부합니다.

[Tales of Destiny DC Clear Save.zip](https://github.com/user-attachments/files/16913754/Tales.of.Destiny.DC.Clear.Save.zip)

**Comment by kexplo** [comment]
![Image](https://github.com/user-attachments/assets/2a8178cd-d262-4892-b601-7861ce38ec65)

제보 고맙습니다. 다음 패치에 수정 적용 예정입니다.
