### ISSUE TITLE
[버그 제보]: 죠니 서브이벤트 중 멈춤 현상 버그

### ISSUE THREAD

**Issue by LeeJangHo2000** [ToD-DC-Kor/kor-patch#481]
### 버그에 대한 설명

토케이령으로 갔다가 시덴으로 돌아가서 죠니방의 초록색옷 npc에게 말을 걸면 멈춥니다.

### 버그 재현 방법

파일은 7번 세이브 파일 입니다.

찾아낸 버그는 총 2개입니다.

[memcards.zip](https://github.com/user-attachments/files/17304311/memcards.zip)

소리유락인 서브스토리중 토케이령으로 갔다가 다시 시덴의 죠니의 방으로 들어와서 악기쪽으로 다가가면 자동 이벤트 발생 
이벤트 발생시 멈춤 버그 발생

원판에서 해결후 그자리에서 퀘스트 완료 뒤 중단 후 한글판 0.7패치에서 밑층으로 내려가면 다시 멈춤현상 발생

-추가 제보 입니다. 서브 이벤트 종료 후 다시 2층의 죠니의 방으로 입장 시 기존에 있었던 입장버그가 다시 발생합니다.

### 패치 버전

0.7

### PCSX2 버전

2.0.2

### 체크리스트

- [ ] 한국어 패치 되지 않은 버전에서도 문제가 발생합니다
- [x] 한국어 패치 된 버전에서만 문제가 발생합니다
- [x] v0.2.1 패치 버전 이후에 작성된 세이브 파일로 진행했습니다
- [ ] 최신 한국어 패치 버전을 사용했습니다
- [x] 재현 가능한 세이브 파일을 첨부했습니다

**Comment by kexplo** [comment]
#453 과 같은 버그로 보이고, 0.8.0-beta 에서 재현되지 않습니다.

**Comment by LeeJangHo2000** [comment]
확인결과 0.8 버전에선 두 버그 모두 재현되지 않습니다.
