### ISSUE TITLE
줄넘김 미적용 이슈

### ISSUE THREAD

**Issue by kexplo** [ToD-DC-Kor/kor-patch#482]
0.8.0-beta 이후로 줄넘김이 되고 있는지 확인 필요 

![20240926052657_1](https://github.com/user-attachments/assets/938431bd-7ca4-4b23-bc6d-0144c961c929)

_Originally posted by @dj5927 in https://github.com/ToD-DC-Kor/kor-patch/pull/100#discussion_r1779643148_

**Comment by dj5927** [comment]
[![Image](https://github.com/user-attachments/assets/e8bb280f-05e0-4d81-9304-480bdb3a5eeb)

리온 사이드 진행중에는 일단 줄넘김 잘 적용되었습니다.

저 대사가 한개뿐인거보면 같은걸 쓸텐데...

스탄쪽 진행중에 한번도 검증이 필요할거 같긴합니다.

**Comment by Sap1in9** [comment]
![Image](https://github.com/user-attachments/assets/50579a80-ce9c-48f9-af67-86e6a422be1b)

스탄사이드 확인 완료

**Comment by kexplo** [comment]
확인 고맙습니다. 🙌
