### ISSUE TITLE
[버그 제보]: 블랙스크린

### ISSUE THREAD

**Issue by nakarydingoo** [ToD-DC-Kor/kor-patch#486]
### 버그에 대한 설명

여왕의 방 진입시 블랙스크린

### 버그 재현 방법

[report.zip](https://github.com/user-attachments/files/17437103/report.zip)

세이브 포인트에서 성으로 진입

메인 로비에서 좌측 2층 으로
![Image](https://github.com/user-attachments/assets/5563df1d-fa07-4b91-bc93-79d6edfba27b)

우측방에 입장하면 블랙스크린
![Image](https://github.com/user-attachments/assets/5dd3784f-a696-47d4-af38-d046076abf48)

### 패치 버전

0.8.0 241010

### PCSX2 버전

2.0.2

### 체크리스트

- [ ] 한국어 패치 되지 않은 버전에서도 문제가 발생합니다
- [x] 한국어 패치 된 버전에서만 문제가 발생합니다
- [ ] v0.2.1 패치 버전 이후에 작성된 세이브 파일로 진행했습니다
- [x] 최신 한국어 패치 버전을 사용했습니다
- [x] 재현 가능한 세이브 파일을 첨부했습니다

**Comment by kexplo** [comment]
`13714_69` 번역파일 이슈

**Comment by kexplo** [comment]
![Image](https://github.com/user-attachments/assets/38aee43f-c3c0-4580-95ce-c67709e8a1f1)

수정 완료
