### ISSUE TITLE
[번역 오류 제보]: 15759_0000 12번 대사중 카이카이가 뭘 말하는걸까요?

### ISSUE THREAD

**Issue by dlatod84** [ToD-DC-Kor/kor-patch#49]
### 번역 오류에 대한 설명

![화면 캡처 2024-09-07 103731](https://github.com/user-attachments/assets/3ae221bd-e4a8-40e2-bbfa-cdd3a98449a2)

15759_0000 12번 대사중 카이카이가 뭘 말하는걸까요?

음식 재료이름인가요?

### 패치 버전

00

**Comment by kexplo** [comment]
원문과 해설입니다

```
そういってもらえると嬉しいぞ。
魁会があれば、また振舞うとしよう。
```

![image](https://github.com/user-attachments/assets/7aa25b4d-e8e6-47dc-91b7-88d500a6a017)

**Comment by dlatod84** [comment]
그렇게 말해주면 기쁠거야.
기회가 있으면 다시 행동하기로 하자.

원문을 파파고로 검색하니 이렇게 나오는군요

**Comment by kexplo** [comment]
"기회가 생길 경우 어떤 행동을 하겠다는 의미를 내포"하는 뜻이라고 하니, 직역하면 파파고 결과처럼 나올 것 같네요. 앞 뒤 맥락을 봐야 자연스럽게 번역할 수 있을 것 같아보입니다.

**Comment by kexplo** [comment]
대화 전체를 더 자연스럽게 번역한 [v0.7.0 버전](https://github.com/ToD-DC-Kor/kor-patch/releases/tag/v0.7.0)이 배포되었습니다.

새 번역에서는 "모임이 있다면, 또 대접하도록 하지"로 번역되었네요.
