### ISSUE TITLE
광범위한 데이터 깨짐

### ISSUE THREAD

**Issue by kexplo** [ToD-DC-Kor/kor-patch#5]
**버그에 대한 설명**
#3 재현 중 발견.
이전에 정상 출력되던 문자열이 광범위하게 깨지고 있음. 원인은 메모리 정렬 어긋남.

**재현 방법**
N/A

**스크린샷**
![Tales of Destiny  Director's Cut _SLPS-25842_20240820235303](https://github.com/user-attachments/assets/0f550d5f-c0b9-4149-bd2c-d065b7f9323f)

**기대결과**
스크린샷 기준으로
- 문장이 한 줄만 나와야 함
- 깨진 글자가 있어서는 안 됨

**실행 환경:**
 - 패치 버전: ~~v1.0.1 이후 발생 ?~~

**Comment by kexplo** [comment]
v0.2.1 패치에서 수정 완료.

![Tales of Destiny  Director's Cut _SLPS-25842_20240821225534](https://github.com/user-attachments/assets/1fcdb7a1-3859-4dcd-a031-3d11e5cc5600)

**Comment by dj5927** [comment]
하멘츠마을 월트집 2층 가면
이벤트가 다 생략되고 이상한 대화 몇번 나오다 바로 밥먹는장면으로 넘어가졌었는데
0.2.1 패치 이후로 정상적으로 진행되네요
