### ISSUE TITLE
[번역 오류 제보]: 

### ISSUE THREAD

**Issue by zysworld** [ToD-DC-Kor/kor-patch#50]
### 번역 오류에 대한 설명

![gsdx_20240907183554](https://github.com/user-attachments/assets/c2791911-a682-4f79-b04c-003a10977ae8)

### 패치 버전

v0.5.1

### 추가 정보

마지막에 일본어가 있네요

**Comment by kexplo** [comment]
제보 고맙습니다. #25 에서 처리되어 다음 패치에 적용 예정입니다.
