### ISSUE TITLE
[번역 오류 제보]: 번역이 안되어 있는 부분

### ISSUE THREAD

**Issue by zysworld** [ToD-DC-Kor/kor-patch#52]
### 번역 오류에 대한 설명

![gsdx_20240907185400](https://github.com/user-attachments/assets/f3025c18-bfb8-4065-9cab-1ae1ff9001a1)
![gsdx_20240907185235](https://github.com/user-attachments/assets/e8ded7a9-842e-43d3-b496-dce4ddc2dba5)
![gsdx_20240907185346](https://github.com/user-attachments/assets/32564b79-0119-4993-82f7-708eb504177f)

### 패치 버전

0.5.1

### 추가 정보

번역이 되어 있지 않는 부분이라 올려봅니다.

**Comment by kexplo** [comment]
![Image](https://github.com/user-attachments/assets/85946371-f0cb-4e6b-b368-dfc9915d7d7e)
![Image](https://github.com/user-attachments/assets/d183d573-bcbf-4195-97cf-69689aea4c43)

최소 v0.8.0 이후로는 해결된 것으로 보이므로 이슈 닫습니다.
