### ISSUE TITLE
[번역 오류 제보]: 끝에 일본어가 나옵니다.

### ISSUE THREAD

**Issue by zysworld** [ToD-DC-Kor/kor-patch#53]
### 번역 오류에 대한 설명

![gsdx_20240907183554](https://github.com/user-attachments/assets/71732b07-82f7-4968-bf12-56f2c87508b7)

### 패치 버전

0.5.1

### 추가 정보

제목과 동일합니다.  끝에 일본어가 하나 들어가 있네요.

**Comment by kexplo** [comment]
v0.6.0에서 고쳐졌을거라고 생각됩니다.
