### ISSUE TITLE
[번역 오류 제보]: 글자 오류

### ISSUE THREAD

**Issue by zysworld** [ToD-DC-Kor/kor-patch#55]
### 번역 오류에 대한 설명

![gsdx_20240907234107](https://github.com/user-attachments/assets/9120c0ee-b6c5-4b15-b6fb-3156af8ac16a)

### 패치 버전

0.5.1

### 추가 정보

음성은 방심은 금물이다 같은데 글자가 깨져서 나옵니다.

**Comment by kexplo** [comment]
v0.6.0에서 해결되었을거라 생각합니다. 만약 아니라면 이슈를 다시 열어주세요.
