### ISSUE TITLE
[버그 제보]: 0.6 패치 이후 전투화면 하단 UI 파티 얼굴 스프라이트가 깨집니다.

### ISSUE THREAD

**Issue by dos1881** [ToD-DC-Kor/kor-patch#56]
### 버그에 대한 설명

그래픽 버그

### 재현 방법

0.6패치 이후 전투화면 하단 파티 얼굴 스프라이트가 깨져서 출력됩니다.

![Tales of Destiny  Director's Cut _SLPS-25842_20240907235754](https://github.com/user-attachments/assets/01aeb8cd-09e5-44b2-9da7-3e92a81e3ed0)

혹시나 해서 에뮬레이터의 랜더러 변경과 다른 분의 세이브 파일로 확인해봐도 동일하게 깨져 나옵니다.

### 패치 버전

0.6

### PCSX2 버전

2.1.127

### 체크리스트

- [ ] 한국어 패치 되지 않은 버전에서도 문제가 발생합니다
- [X] 한국어 패치 된 버전에서만 문제가 발생합니다
- [X] v0.2.1 패치 버전 이후에 작성된 세이브 파일로 진행했습니다
- [X] 최신 한국어 패치 버전을 사용했습니다

**Comment by zysworld** [comment]
저도 깨져나오네요.
![gsdx_20240908000802](https://github.com/user-attachments/assets/e5040865-303b-48c1-afe8-4ade25e99db9)

**Comment by zysworld** [comment]
0.6.1 부터 잘 나오네요. 감사합니다.
