### ISSUE TITLE
문자열 넘침 버그 수정 필요

### ISSUE THREAD

**Issue by kexplo** [ToD-DC-Kor/kor-patch#58]
#38 이슈

재현 세이브 파일: https://github.com/ToD-DC-Kor/kor-patch/issues/38#issuecomment-2334616642

위 케이스에 대해서는 13693_41, 13707_35 그리고 .13709_34, 13695_34에 영향이 있을 것으로 보임

위 세이브파일로 당장 재현할 수 있는 케이스는 13695_34

**Comment by Sap1in9** [comment]
![image](https://github.com/user-attachments/assets/37e97287-6b6f-493e-8602-177f4cb1906f)
마리 칭호 획득 후 튜토리얼 문자열 넘침 버그
세이브파일 : [ToD_DC_001_240910.zip](https://github.com/user-attachments/files/16959809/ToD_DC_001_240910.zip)
재현 : 세이브 16번 슬롯 불러오기 → 여관 나와서 우측 위 구역으로 → 제일 우측 집에 들어가서 노인과 대화
![image](https://github.com/user-attachments/assets/244964c2-61cd-471a-87d4-209e6e8b5302)

**Comment by kexplo** [comment]
최신 번역에서는 개행처리 된 것으로 확인하여 이슈 종료합니다. (만약 아니라면 다시 열어주세요)
