### ISSUE TITLE
[번역 오류 제보]: 오타 제보

### ISSUE THREAD

**Issue by zysworld** [ToD-DC-Kor/kor-patch#60]
### 번역 오류에 대한 설명

![gsdx_20240908170151](https://github.com/user-attachments/assets/b6d59f3e-d5ad-42de-87b8-01bea7e6b18a)

### 패치 버전

0.6.0

### 추가 정보

객원 검뚱으로 나오네요.

**Comment by kexplo** [comment]
대화 전체를 더 자연스럽게 번역한 [v0.7.0 버전](https://github.com/ToD-DC-Kor/kor-patch/releases/tag/v0.7.0)이 배포되었습니다.
기존의 문제가 여전한지 다시 확인 부탁드립니다.
