### ISSUE TITLE
[번역 오류 제보]: 번역 오류

### ISSUE THREAD

**Issue by zysworld** [ToD-DC-Kor/kor-patch#61]
### 번역 오류에 대한 설명

![gsdx_20240908172946](https://github.com/user-attachments/assets/3531a429-9afe-4e17-a0d1-c117fe8b2baf)

### 패치 버전

0.6.0

### 추가 정보

나가라고 하는데 흐름상 나와가 맏는것 같네요.

**Comment by kexplo** [comment]
대화 전체를 더 자연스럽게 번역한 [v0.7.0 버전](https://github.com/ToD-DC-Kor/kor-patch/releases/tag/v0.7.0)이 배포되었습니다.
기존의 문제가 여전한지 다시 확인 부탁드립니다.
