### ISSUE TITLE
[번역 오류 제보]:  번역 오류 제보

### ISSUE THREAD

**Issue by zysworld** [ToD-DC-Kor/kor-patch#63]
### 번역 오류에 대한 설명

[
![gsdx_20240908173754](https://github.com/user-attachments/assets/f33463ca-25f3-4d47-a647-22979cdf0674)
![gsdx_20240908173757](https://github.com/user-attachments/assets/16db42a9-c623-409d-9dfe-a0228407b1a3)
](url)

### 패치 버전

0.6.0

### 추가 정보

당신, 잘도 신나서 돌아다니네 - 신나서 떠드는 상황입니다.
국왕 폐하의 앞이다 모두 대기하라 - 정숙하라고 하는 것이 상황이 맞느것 같은데

**Comment by kexplo** [comment]
대화 전체를 더 자연스럽게 번역한 [v0.7.0 버전](https://github.com/ToD-DC-Kor/kor-patch/releases/tag/v0.7.0)이 배포되었습니다.
기존의 문제가 여전한지 다시 확인 부탁드립니다.
