### ISSUE TITLE
칭호 설정 가이드 텍스트 가로 길이 넘침

### ISSUE THREAD

**Issue by dos1881** [ToD-DC-Kor/kor-patch#7]
**버그에 대한 설명**
다릴셰이드 도착 후 첫 칭호를 획득한 다음 칭호에 대한 설명창이 화면을 벗어난 상태로 출력됩니다.

**스크린샷**
![Tales of Destiny  Director's Cut _SLPS-25842_20240822151722](https://github.com/user-attachments/assets/27ef6fe9-e4d7-44b4-8af5-6e019a77f079)

**실행 환경:**
 - 패치 버전: 0.2.1
 - PCSX2 버전: 2.1.102

**
데이터 깨짐을 수정해주신 덕분인지 아니면 에뮬레이터의 테일즈 오브 데스티니 전용 핵 옵션인 FPU 멀티플라이 핵을 
킨 상태로 진행해서인지 처음부터 새로 시작해서 다릴셰이드까지 진행 중 나오는 모든 NPC들에게도 한 번씩은 다 대화를 
걸어보고 스킷도 전부 재생해봤지만 아직까진 프리징 현상은 없는 상태입니다.

**Comment by kexplo** [comment]
초반 프리징 현상이 완화되었다니 좋은 소식이네요!
데이터 깨짐 현상이 꽤 심각했어서 아마 많이 불안정한 상태였을 것이라 추정됩니다. 기존에 발생하던 프리징 현상은 정확한 재현 스탭이 없어서 정확한 인과관계를 파악하긴 힘들지만요.

제보해주신 것은 번역쪽 이슈로 보입니다. 일본어를 한국어로 번역하면서 가로 길이가 더 길어지는 경우가 있을텐데, 딱 그 경우로 보이네요.

모든 번역 데이터를 저장소에 공개 중이니, 직접 검색해서 확인해 볼 수도 있습니다:

https://github.com/search?q=repo%3AToD-DC-Kor%2Fkor-patch+%EC%B9%AD%ED%98%B8%EB%A5%BC+%EC%84%A4%EC%A0%95%ED%95%98%EA%B3%A0+%EC%9D%B4%EC%95%BC%EA%B8%B0%ED%95%A8%EC%9C%BC%EB%A1%9C%EC%8D%A8&type=code

대사의 줄바꿈 부분을 일괄로 교정해주면 해결 될 것으로 보입니다.

덕분에 문제가 있다는 것을 알았으니, 나중에 교정하겠습니다.
아니면 직접 수정해서 Pull Request 올려주셔도 좋을 것 같아요. 😄

**Comment by kexplo** [comment]
수정: https://github.com/ToD-DC-Kor/kor-patch/commit/7aecf70622c2803bd906b8e5e084859fefcf77bf

일괄 치환했으니 아마 잘 나올거라고 생각합니다.
테스트해 볼 환경이 없어서 확인은 못 했습니다.
