### ISSUE TITLE
[번역 오류 제보]: 그레밤과 전투 후 비행룡 대화 + 리네마을 대화에서

### ISSUE THREAD

**Issue by qnffngofl** [ToD-DC-Kor/kor-patch#70]
### 번역 오류에 대한 설명

![KakaoTalk_20240910_125011255](https://github.com/user-attachments/assets/efc389e8-3edc-4530-992a-58b9978b84da)

1. 멀미하는 리온에게 샤르티에가 하는 대사에서
    "도련님"이  "부잣집 아가씨"로 번역된 케이스

2. 이미지는 없지만 1부 종료 직전 1부 엔딩에서 3개월 후 리리스가 스탄을 깨우는 장면에서 
    오니쨩(대사) "오빠"가 "형"으로 오번역됨.

### (선택사항) 재현 방법

그레밤과 전투 후 비행룡 컷씬에

### 패치 버전

v0.6.1

### 추가 정보

다른 자료 공유차 

저의 동일 아이디 네이버 메일(qnffngofl@naver.com)로 

me@chanwoong.kim 주소로 메일 전송 드렸습니다.

시간 나실때 확인 부탁드립니다.

**Comment by kexplo** [comment]
대화 전체를 더 자연스럽게 번역한 [v0.7.0 버전](https://github.com/ToD-DC-Kor/kor-patch/releases/tag/v0.7.0)이 배포되었습니다.
번거롭겠지만 한 번 더 확인 부탁드리겠습니다.
