### ISSUE TITLE
하이델베르크 이벤트 대사 순서 깨짐

### ISSUE THREAD

**Issue by jessypark7979** [ToD-DC-Kor/kor-patch#8]
**스크린샷**

![Tales of Destiny  Director's Cut _SLPS-25842_20240823111800](https://github.com/user-attachments/assets/61a8bd8a-3d57-4af1-866d-2aadd3e4c97e)
![Tales of Destiny  Director's Cut _SLPS-25842_20240823111825](https://github.com/user-attachments/assets/0542b579-d246-4b59-b2c7-796a3897e431)

**실행 환경:**
 - 패치 버전: v0.2.1
 - PCSX2 버전: pcsx2-v2.1.102

**추가 정보**
하이델베르크 진입 후 출력 되는 대사가 실제 대사와 일치 하지 않아요.

**Comment by kexplo** [comment]
이름이랑 대사 순서가 바뀐 것을 보니, 번역 데이터에 일부 누락된 것 같네요. 혹시 이벤트 직전 세이브 제공이 가능할까요?

**Comment by dj5927** [comment]
0.2.1 패치 이전 데이터로 진행중이면 0.2.1 패치후 새로운게임으로 다시 진행해보세요

저도 다른구간에 비슷한 현상이 있었는데 0.2.1 패치후 첨뷰터 다시하니 해결됬습니다

**Comment by jessypark7979** [comment]
1.2.3번 세이브가 1차 진입

5.6.7번 세이브가 2차 진입 상태 입니다.

마을로 바로 진입 하시면 이벤트 진행 됩니다.


[TalesOfdestinydc Hangle test 1.zip](https://github.com/user-attachments/files/16723560/TalesOfdestinydc.Hangle.test.1.zip)

**Comment by jessypark7979** [comment]
> 0.2.1 패치 이전 세이브 데이터로 진행중이였다몀 0.2.1 패치후 새로운게임으로 다시 진행해보세요
> 
> 저도 다른구간에 비슷한 현상이 있었는데 0.2.1 패치후 첨뷰터 다시하니 해결됬습니다
> 
> 0.2.1 이전에 진향하던 세이브들은 어딘가 다 망가진거 같습니다.

같은 세이브로 이어서 해도 패치마다 다르게 나오네요.

처음부터 다시 해야 될 것 같네요.

**Comment by jessypark7979** [comment]
[TalesOfdestinydc Hangle test 1.zip](https://github.com/user-attachments/files/16726437/TalesOfdestinydc.Hangle.test.1.zip)
혹시 몰라 세이브 파일 올려 놓습니다.

**Comment by kexplo** [comment]
@jessypark7979, 재현되는 세이브 덕분에 문제를 금방 찾았네요. 👍 

데이터에 오류가 있었고, 다음 배포에 수정 예정입니다. 비슷한 오류가 더 있을 것 같은데, 일괄 검수 해야겠네요.

수정 패치: https://github.com/ToD-DC-Kor/kor-patch/commit/68a4dfcc88d75148fd8f55c85924f5d90ff9349c

**Comment by kexplo** [comment]
[v0.3.0](https://github.com/ToD-DC-Kor/kor-patch/releases/tag/v0.3.0)에서 수정 완료

**Comment by jessypark7979** [comment]
> [v0.3.0](https://github.com/ToD-DC-Kor/kor-patch/releases/tag/v0.3.0)에서 수정 완료

다른 이벤트 후에 하이델베르크 2차 이벤트 시에도 대사가 밀림 현상이 있습니다.



![Tales of Destiny  Director's Cut _SLPS-25842_20240823130824](https://github.com/user-attachments/assets/b8d00611-0653-4349-80d8-587a73dfdc23)
![Tales of Destiny  Director's Cut _SLPS-25842_20240823131203](https://github.com/user-attachments/assets/83113bbf-471c-4914-a83a-11d1f497e5b8)

**Comment by kexplo** [comment]
2차 이벤트라고 지칭하신 게 다른 파일이었나 보군요

**Comment by kexplo** [comment]
'2차 이벤트' 재현 조건을 적어주실 수 있나요? @jessypark7979

**Comment by kexplo** [comment]
수정: https://github.com/ToD-DC-Kor/kor-patch/commit/e75cb0d2270c4d090eb2bbb93b5a10c56fa3ceb7

비슷하게 깨진 파일들 일괄 교정했으니 아마 잘 나올거라고 생각합니다.
재현되면 다시 제보해주세요.
